name: Test

on: [push,pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install SWI-Prolog backend
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: stable
          swi-prolog-version: latest
      - name: Intall required packs
        run: |
          sudo apt install raptor2-utils
          sudo apt-get install libserd-dev
          swipl -g "pack_install('https://github.com/GavinMendelGleason/hdt.git',[interactive(false)])" -t halt
          swipl -g "pack_install(mavis,[interactive(false)])" -t halt
          swipl -g "pack_install(terminus_store_prolog,[interactive(false)])" -t halt
      - name: Install HDT Library
        run: |
          cd ~
          git clone https://github.com/rdfhdt/hdt-cpp
          cd hdt-cpp
          ./autogen.sh
          ./configure
          make -j2
          sudo make install
      - name: Checkout application to be tested
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true
      - name: Initialize the database
        run : |
          utils/db_util -k "test123" -s "test_server"
      - name: Run the application tests
        run: |
          ./start.pl test
